### ISSUE TITLE
404 Endpoint "GET /graphql" not found.

### ISSUE THREAD

**Issue by wachyudisonang** [strongloop/loopback4-example-family-tree#5]
Hi, I just clone your awesome work but suddenly I got "NotFoundError" 
404 Endpoint "GET /graphql" not found.

What should I do to fix this?

**Comment by Alan-Cha** [comment]
@wachyudisonang Sorry to hear that the tutorial isn't working correctly! Will take a look at it...

**Comment by Alan-Cha** [comment]
@wachyudisonang Sorry for the long wait. I think I fixed the problem. There were some port changes (from 3001 to 3000) that were not reflected in the documentation. If you are still trying out LoopBack/OpenAPI-to-GraphQL, please let me know if you still encounter any issues. Otherwise, thanks for reporting this!
